name: catch_and_share

services:
  web:
    restart: unless-stopped
    container_name: catch_and_share-web
    build:
      dockerfile: ./Dockerfile
      context: ./
    volumes:
      - /var/catch-and-share_data/database.sqlite:/app/database/database.sqlite
      - /var/catch-and-share_data/storage:/app/storage/
    ports:
      - 127.0.0.1:8001:80
